apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: cache
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "docker/default" 
spec:
  containers:
  - name: redis
    image: us.gcr.io/{{PROJECT_ID}}/redis:0.1
    imagePullPolicy: Always
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    lifecycle:
      postStart:
        exec:
          command: ["/init_redis.sh"]
    resources:
      limits:
        cpu: "128Mi"
        memory: "500m"
      requests:
        cpu: "100m"
        memory: "64Mi"
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsUser: 50000
      runAsNonRoot: true
      capabilities:
        drop:
         - NET_RAW
         - ALL