name: Checkov
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python $
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
      - name: Scan k8s dashboard manifests
        run: |
          pip install checkov
          checkov -d examples/dashboard --framework kubernetes
      - name: Scan k8s namespace manifests
        run: |
          pip install checkov
          checkov -d examples/namespace --framework kubernetes
      - name: Scan k8s redis manifests
        run: |
          pip install checkov
          checkov -d examples/redis --framework kubernetes
      - name: Scan k8s secrets manifests
        run: |
          checkov -d examples/secrets --framework kubernetes