name: Checkov
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python $
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.2
      - name: Scan k8s manifests 
        run: |
          pip install checkov
          checkov -d examples/redis --framework kubernetes
          #checkov -d corrected-examples/redis --framework kubernetes --skip-check CKV_K8S_29,CKV_K8S_38,CKV_K8S_8,CKV_K8S_43,CKV_K8S_9